from BasePackage.Base import Base
from Utilities.Waits import Wailts
import time

b=Base()
w=Wailts()

w.waitA(150)
b.AndroidDriver.quit()

b.AndroidDriver.find_element_by_id('btn_register').click()
b.AndroidDriver.find_element_by_id('et_email').send_keys('validUser9@protius.com')
b.AndroidDriver.find_element_by_id('btn_next').click()
b.AndroidDriver.find_element_by_id('cb_policy_agreement').click()
b.AndroidDriver.find_element_by_id('btn_i_agree').click()
b.AndroidDriver.find_element_by_xpath('//android.widget.RelativeLayout').is_displayed()
b.AndroidDriver.find_element_by_id('btn_action_positive').click()
b.AndroidDriver.find_element_by_id('et_start_code').send_keys('mobile')
b.AndroidDriver.find_element_by_id('btn_next').click()
b.AndroidDriver.find_element_by_id('et_patient_id').send_keys('PP1234')
b.AndroidDriver.find_element_by_id('btn_next').click()
b.AndroidDriver.find_element_by_id('et_first_name').send_keys('Colonel Nick')
b.AndroidDriver.find_element_by_id('et_last_name').send_keys('Fuery')
b.AndroidDriver.find_element_by_id('btn_next').click()
b.AndroidDriver.find_element_by_id('et_phone').send_keys('1234567890')
b.AndroidDriver.find_element_by_id('btn_next').click()
b.AndroidDriver.find_element_by_id('et_dob').click()
for i in range(10):
    b.AndroidDriver.find_element_by_xpath('//android.widget.NumberPicker[1]/android.widget.Button[2]').click()
    b.AndroidDriver.find_element_by_xpath('//android.widget.NumberPicker[2]/android.widget.Button[2]').click()
    b.AndroidDriver.find_element_by_xpath('//android.widget.NumberPicker[3]/android.widget.Button[2]').click()
b.AndroidDriver.find_element_by_id('btn_action_positive').click()
b.AndroidDriver.find_element_by_id('btn_next').click()
b.AndroidDriver.find_element_by_id('et_password').send_keys('1234567890')
b.AndroidDriver.find_element_by_id('btn_next').click()
b.AndroidDriver.find_element_by_id('btn_skip_for_now').click()
b.AndroidDriver.find_element_by_id('btn_action_positive').click()
b.AndroidDriver.find_element_by_id('btn_action_positive').click()
b.AndroidDriver.find_element_by_id('btn_yes').click()
assert b.AndroidDriver.find_element_by_id('tv_patch_status').is_enabled()
E=b.AndroidDriver.find_element_by_id('tv_menu')
assert E.is_enabled()
E.click()
time.sleep(2)
E=b.AndroidDriver.find_element_by_xpath('//android.support.v7.widget.LinearLayoutCompat[5]/android.widget.CheckedTextView')
assert E.is_enabled()
E.click()
b.AndroidDriver.find_element_by_id('tv_lbl_password_pin').click()
b.AndroidDriver.find_element_by_id('frame_change_password').click()
b.AndroidDriver.find_element_by_id('et_password').send_keys('1234567890')
b.AndroidDriver.find_element_by_id('btn_next').click()
b.AndroidDriver.find_element_by_id('et_password').send_keys('0987654321')
b.AndroidDriver.find_element_by_id('btn_next').click()
b.AndroidDriver.find_element_by_id('btn_action_positive').click()
b.AndroidDriver.find_element_by_id('tv_back').click()
b.AndroidDriver.find_element_by_id('tv_editProfile_signOut').click()
b.AndroidDriver.find_element_by_id('btn_action_positive').click()
E=b.AndroidDriver.find_element_by_xpath('//android.widget.ImageView')
assert E.is_displayed()
b.AndroidDriver.quit()